application: gentle-broker-850
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /images/(.*)
  static_files: images/\1
  upload: images/.*